car_service_admin:
    resource: "@CarServiceAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

car_service_app:
    resource: "@CarServiceAppBundle/Controller/"
    type:     annotation
    prefix:   /

